name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: actions checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '14.x'

    - name: script
      working-directory: ./angular-app
      run: |
        npm install -g @angular/cli
        npm install
        ng build --prod --base-href="/paw2020/"
    - name: Deploy Pages
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: angular-app/dist/angular-app
  deploy:
      runs-on: ubuntu-latest
      name: Deploy Heroku
      steps: 
        - name: Checkout
          uses: actions/checkout@v2
          with:
            persist-credentials: false
        - name: Add remote origin
          run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        - name: Deploy backend to heroku
          run: git push --force heroku `git subtree split --prefix restAPI HEAD`:master   
          #run: git subtree push --prefix restAPI heroku master
        

