name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: actions checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '14.x'

    - name: script
      working-directory: ./angular-app
      run: |
        npm install -g @angular/cli
        npm install
        ng build --prod --base-href="/paw2020/"
<<<<<<< HEAD
        mkdir public
        mv dist/angular-app/* public
    - name: GitHub Pages
=======
    - name: Deploy
>>>>>>> 81966d7bfeb459099e9d4c95c18aff8104dcef99
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: angular-app/dist/angular-app
        

