# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, pages ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.17.0

    - name: script
      run: |
        npm install -g angular-app/ @angular/cli
        npm install /angular-app/
        ng build --base-href=/angular-app/
        mkdir public
        mv dist/angular-app/* public
      env:
        CI: true
