# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '14.x'

    - name: script
      working-directory: ./angular-app
      run: |
        npm install -g @angular/cli
        npm install
        ng build --prod --base-href="/angular-app/"
        mkdir public
        mv dist/angular-app/* public
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        repo: paw2020
        target_branch: gh-pages
        build_dir: angular-app/dist/angular-app
