name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: actions checkout
      uses: actions/checkout@v2
      
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.ACCESS_TOKEN }}

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '14.x'

    - name: script
      working-directory: ./angular-app
      run: |
        npm install -g @angular/cli
        npm install
        ng build --prod --base-href="/paw2020/"
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: angular-app/dist/angular-app
        

